version: '3.8'

# TODO
services: 
  mongodb-server-configsvr:
    container_name: exert-mongodb-configsvr
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - "27041:27017"
    volumes:
      - ./asset/c1/data:/data/db
      - ./asset/c1/conf:/data/configdb:ro
    networks:
      - exert-mongodb-sc-net

networks:
  exert-mongodb-sc-net:
    name: exert-mongodb-sc-net
    driver: bridge